# Site settings
title: Copehouse
email: me@myhouse.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site.  There are many like it, but this one is mine
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.copehouse.com" # the base hostname & protocol for your site
twitter_username: scopey
github_username:  scopey

# Build settings
markdown: kramdown
